### PR TITLE
Crud operations runs

### PR DESCRIPTION
**Pull request by LaraMo**
**Describe the pull request**
A util method for CRUD operations. 

# Validation
### **C**reate 
 Adds a new run to the db when the user saves their run by pressing the following icon:
image

Code:
```js  
  FirestoreCRUDUtil firestoreCRUD = new FirestoreCRUDUtil();
  firestoreCRUD.createEntry("runs", run);
 
```
Results:
image
image
-----------------------------
### **R**ead 
Will get a specific entry. 
Finds an entry by documentId (which is also the track.getUuid() value) 

Code:
```js  
       Map<String, Object> updateRun = new HashMap<>();
       updateRun.put("id",127);
       updateRun.put("ascent",1);
       firestoreCRUD.updateEntry("runs", updateRun);
```
-----------------------------
### **U**pdate 
Will modify a specific entry. 
Finds an entry by documentId (which is also the track.getUuid() value) 

Code:
```js  
        Map<String, Object> getRun = new HashMap<>();
        getRun.put("id",123);
        firestoreCRUD.getEntry("runs", getRun);
 
```

Results:
image

-----------------------------

Results:
image

-----------------------------
### **D**elete
Will delete a specific entry. 
Finds an entry by documentId (which is also the track.getUuid() value) 

Code:
```js  
       Map<String, Object> deleteRun = new HashMap<>();
       deleteRun.put("id",134);
       firestoreCRUD.deleteEntry("runs", deleteRun); 
```
Results:
134 isn't present anymore
image

**Link to the the issue**
(If available): The link to the issue that this pull request solves.

**License agreement**
By opening this pull request, you are providing your contribution under the _Apache License 2.0_ (see [LICENSE.md](LICENSE.md)).

**Note: new dependencies/libraries**
Please refrain from introducing new libraries without consulting the team.

### CODE REVIEW

**Comment by AxelMoranC** [comment]
Very good. approved on my end.

**Review by AxelMoranC — COMMENTED** [review]
great! approved

**Review by aliL123 — APPROVED** [review]
No issues here, looks great. Nice job!

**Comment by TerrylForyoung** [comment]
Looks great!

**Comment by jeanrobatto** [comment]
I think we should aim to use the JSON type from the gson google lib, not a Map<String, Object>

This is simply bc they are not the same type, for example this would be a valid map but invalid json:

{
 "person": Person
}

I know the documentation shows this, but imo its not an ideal use of strongly typed features

Essentially we have POJO Models that are already used internally as DTOs and for the SQLite persistence, and for the noSQL external database we know we need JSON, hence the serialization. If FireStore requires the Map<String, Object> I would personally opt for the adapter pattern to simply convert our generinc noSQL JSON type to the Map but only specifically for FireStore

I know it sounds nit picky, but the current implementation does not use my serialization at all, we need to construct the map manually every time, its not ideal

I would use static constants for the table names, not strings, and same thing for your Log TAGS in the crud util

now you have for example "runs" passed as argument to your functions, imagine what would happen if the "runs" files is renamed to "tracks" for example, we'd need to update a ton of different places

I would create a constants/FireStoreFiles or whatever and just export a final String RUN_TABLE = "runs" 

Typically we want to code to interfaces, not classes

FirestoreCRUDUtil firestoreCRUD = new FirestoreCRUDUtil();

This is generally a bad idea, you should make an abstraction using polymorphism

ExternalStorage firestoreCRUD = new FirestoreCRUDUtil();

Missing docs for the class (awesome for the methods! but its nice to have docs for the class too)

Its a good practice in Java to make everything  final unless you plan on changing it, including parameters received in functions

Not necessarily here, but a note that we'll need good error handling at the top level whenever we call these methods!

**Pull request closed without merging**
